"""add_email_and_otp_tables

Revision ID: 4cc2092b3144
Revises: 27d59052a004
Create Date: 2026-07-13 15:09:10.924318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc2092b3144'
down_revision: Union[str, Sequence[str], None] = '27d59052a004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otps',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.add_column('doctors', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'doctors', ['email'])
    op.add_column('patients', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'patients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'email')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'email')
    op.drop_table('email_otps')
    # ### end Alembic commands ###
